package com.nowcoder.mall.entity;

import java.math.BigDecimal;
import java.sql.Timestamp;

public class Promotion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion.id
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion.name
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion.start_time
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    private Timestamp startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion.end_time
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    private Timestamp endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion.item_id
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion.promotion_price
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    private BigDecimal promotionPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion.id
     *
     * @return the value of promotion.id
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion.id
     *
     * @param id the value for promotion.id
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion.name
     *
     * @return the value of promotion.name
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion.name
     *
     * @param name the value for promotion.name
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion.start_time
     *
     * @return the value of promotion.start_time
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    public Timestamp getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion.start_time
     *
     * @param startTime the value for promotion.start_time
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    public void setStartTime(Timestamp startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion.end_time
     *
     * @return the value of promotion.end_time
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    public Timestamp getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion.end_time
     *
     * @param endTime the value for promotion.end_time
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    public void setEndTime(Timestamp endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion.item_id
     *
     * @return the value of promotion.item_id
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion.item_id
     *
     * @param itemId the value for promotion.item_id
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion.promotion_price
     *
     * @return the value of promotion.promotion_price
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    public BigDecimal getPromotionPrice() {
        return promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion.promotion_price
     *
     * @param promotionPrice the value for promotion.promotion_price
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    public void setPromotionPrice(BigDecimal promotionPrice) {
        this.promotionPrice = promotionPrice;
    }
    /**
     * 获取活动状态
     *
     * @return -1: 活动未开始, 0: 活动进行中, 1: 活动已结束.
     */
    public int getStatus() {
        Timestamp now = new Timestamp(System.currentTimeMillis());
        if (now.before(startTime)) {
            return -1;
        } else if (now.after(endTime)) {
            return 1;
        } else {
            return 0;
        }
    }
}