package com.nowcoder.mall.dao;

import com.nowcoder.mall.entity.Item;
import com.nowcoder.mall.entity.ItemStock;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ItemStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    int insert(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    ItemStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    List<ItemStock> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    int updateByPrimaryKey(ItemStock record);
    /**
     * 根据商品id 查库存
     */
    ItemStock selectByItemId(Integer itemId);

    /**
     * 扣减库存
     */
    int decreaseStock(Integer itemId,Integer amount);
}