package com.nowcoder.mall.dao;

import com.nowcoder.mall.entity.Promotion;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface PromotionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    int insert(Promotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    Promotion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    List<Promotion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    int updateByPrimaryKey(Promotion record);

    /**
     * 根据商品id查活动
     */
    Promotion selectByItemId(Integer itemId);
}