package com.nowcoder.mall.dao;

import com.nowcoder.mall.entity.SerialNumber;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface SerialNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serial_number
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serial_number
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    int insert(SerialNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serial_number
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    SerialNumber selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serial_number
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    List<SerialNumber> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table serial_number
     *
     * @mbg.generated Sun Nov 14 12:53:42 CST 2021
     */
    int updateByPrimaryKey(SerialNumber record);
}